import { Menu } from "@/models/menu-models"
import {
  Home,
  Package,
  Users,
  BookMinus,
  Settings,
  SquareTerminal,
  Rocket,
  LineChart,
  Sparkles,
  GitBranch,
  Shield,
  Database,
  Globe2,
  Wrench,
  Key,
  Lock,
  Gauge,
  Zap,
} from "lucide-react"

/** Sidebar IA aligned with Blocks Cloud shell (Overview → hub services → project scope). */
export const navigationMenus: Menu[] = [
  {
    id: "overview-project",
    type: "menu",
    name: "Overview",
    path: "/dashboard",
    icon: Home,
  },
  {
    type: "separator",
    id: "separator-overview",
  },
  {
    id: "code-studio",
    type: "menu",
    name: "Code Studio",
    path: "/services/code-studio",
    icon: SquareTerminal,
    badge: "alpha",
  },
  {
    id: "deployment",
    type: "menu",
    name: "Deployment",
    path: "/services/deployment",
    icon: Rocket,
  },
  {
    id: "service-observability",
    type: "menu",
    name: "Observability",
    path: "/services/lmt",
    icon: LineChart,
    children: [
      {
        id: "service-observability__lmt",
        type: "menu",
        name: "LMT",
        path: "/services/lmt",
        icon: Zap,
      },
      {
        id: "service-observability__rate-limiter",
        type: "menu",
        name: "Rate limiter",
        path: "/services/rate-limiter",
        icon: Gauge,
      },
      {
        id: "service-observability__auth-logs",
        type: "menu",
        name: "Authentication logs",
        path: "/services/authentication/logs",
        icon: LineChart,
      },
    ],
  },
  {
    id: "service-ai",
    type: "menu",
    name: "AI",
    path: "/services/secret-management",
    icon: Sparkles,
    children: [
      {
        id: "service-ai__models",
        type: "menu",
        name: "AI models",
        path: "/services/secret-management?tab=ai-models",
        icon: Sparkles,
      },
      {
        id: "service-ai__managed-services",
        type: "menu",
        name: "Managed services",
        path: "/managed-services",
        icon: Settings,
      },
    ],
  },
  {
    id: "workflow",
    type: "menu",
    name: "Workflow",
    path: "/services/workflow",
    icon: GitBranch,
  },
  {
    id: "service-identity",
    type: "menu",
    name: "Identity",
    path: "/services/authentication",
    icon: Shield,
    children: [
      {
        id: "service-identity__authentication",
        type: "menu",
        name: "Authentication",
        path: "/services/authentication",
        icon: Key,
      },
      {
        id: "service-identity__authorization",
        type: "menu",
        name: "Access manager",
        path: "/services/iam",
        icon: Shield,
      },
      {
        id: "service-identity__api-settings",
        type: "menu",
        name: "API settings",
        path: "/services/api-settings",
        icon: Settings,
      },
      {
        id: "service-identity__secret-management",
        type: "menu",
        name: "Secrets & configs",
        path: "/services/secret-management",
        icon: Lock,
      },
    ],
  },
  {
    id: "service-data",
    type: "menu",
    name: "Data",
    path: "/services/data-gateway",
    icon: Database,
    children: [
      {
        id: "service-data__gateway",
        type: "menu",
        name: "Data Gateway",
        path: "/services/data-gateway",
        icon: Database,
      },
      {
        id: "service-data__storage",
        type: "menu",
        name: "Storage",
        path: "/services/storage",
        icon: Database,
      },
    ],
  },
  {
    id: "localization",
    type: "menu",
    name: "Localization",
    path: "/services/localization",
    icon: Globe2,
  },
  {
    id: "utilities",
    type: "menu",
    name: "Utilities",
    path: "/services/utilities",
    icon: Wrench,
  },
  {
    type: "separator",
    id: "separator-identity",
  },
  {
    id: "environments",
    type: "menu",
    name: "Environments",
    path: "/project-overview/environments",
    icon: Package,
  },
  {
    id: "people",
    type: "menu",
    name: "People",
    path: "/project-overview/people",
    icon: Users,
  },
  {
    id: "repositories",
    type: "menu",
    name: "Repositories",
    path: "/project-overview/repositories",
    icon: BookMinus,
  },
  {
    id: "settings",
    type: "menu",
    name: "Project Settings",
    path: "/project-overview/settings",
    icon: Settings,
  },
]
